name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: sudo apt-get install libboost-program-options-dev
    - name: install openmpi
      run: sudo apt-get install libopenmpi-dev openmpi-common
    - name: install eigen3
      run: sudo apt-get install libeigen3-dev
    - name: install intel tbb
      run: sudo apt-get install libtbb-dev
    - name: install spdlog
      run: sudo apt-get install libspdlog-dev
    - name: bootstrap
      run: . bootstrap.sh
    - name: configure
      run: mkdir build && cd build && cmake .. -DBUILD_TESTING=ON -DSEWAS_DISTRIBUTED=OFF -DSEWAS_WITH_PARSEC=OFF -DVERBOSE=ON && cd -
    - name: build
      run: cd build && make && cd -
    - name: test
      run: cd build && ctest --output-on-failure
